version: "2"
services:
    mysql:
      image: mysql:5.7
      container_name: ${PROJECT}-mysql
      volumes:
        - ./data/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      networks:
        - default


    webserver:
      image: nginx
      container_name: ${PROJECT}-webserver
      working_dir: /www
      volumes:
          - ../../../www:/www
          - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
      restart: always
      links:
        - php-fpm
      networks:
        - default
      environment:
        - VIRTUAL_HOST=${VIRTUAL_HOST}
        - LETSENCRYPT_HOST=${VIRTUAL_HOST}
        - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      command: /bin/bash -c "envsubst '$$VIRTUAL_HOST' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"


    php-fpm:
      build: php-fpm
      container_name: ${PROJECT}-php-fpm
      working_dir: /www
      restart: always
      volumes:
        - ../../../www:/www
        - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      networks:
        - default
      links:
        - mysql

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: ${PROJECT}-phpmyadmin
      environment:
        - VIRTUAL_HOST=pma.${VIRTUAL_HOST}
        - LETSENCRYPT_HOST=pma.${VIRTUAL_HOST}
        - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
        - PMA_HOST=mysql
      restart: always
      networks:
        - default
      volumes:
        - /sessions
      links:
        - mysql

    gulp:
      build: node
      container_name: ${PROJECT}-node
      working_dir: /www
      volumes:
        - ../../../www:/www


networks:
  default:
    external:
      name: ${DOCKER_NETWORK}
